### ISSUE TITLE
Regex Flag

### ISSUE THREAD

**Issue by agoora** [crissyfield/troll-a#1]
Hi,
It would be of great interest if you could add a flag to allow a quick search with a regex expression, such as:
flags:
` -regex, --regex expression`
Please implement this option.
Regards.

**Comment by tja** [comment]
Thanks for filing the issue. I'll look into this now.

**Comment by tja** [comment]
This has been added via new `--custom`/`-c` switches, check the README. I'll cut a new release in a minute.
